age_keys: &age_keys
  - "age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6" # local
  - "age1j0ygceakvw3u5vu8zwe92scxc0y48jsf3c24z99sakjp6mahgghquv4p2q" # nixos-mini1

creation_rules:
  - path_regex: .*.(yaml|yml|json|env)$
    age: *age_keys
