age_keys: &age_keys
  - "age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6" # local
  - "age1j0ygceakvw3u5vu8zwe92scxc0y48jsf3c24z99sakjp6mahgghquv4p2q" # nixos-mini1
  - "age1e45kyduhv7zjsrj4wnquy4s7v340xze8m60g5u7qak4fvwfdpcjskee943" # nixos-mini3
  - "age1d0jrt7mlu50t4f0wh0t9hrdt23tjx92k57exc3gukx8e87fq35tshxc3as" # nixos-mini3

creation_rules:
  - path_regex: .*.(yaml|yml|json|env)$
    age: *age_keys
