{
	"data": "ENC[AES256_GCM,data:Am56q3nNEqhP/nuJpmE7py3RgLBd4rGcSskj87kEqQXUdRZ2IPo5bsZSFSD7/u9qV4mxkXe6606kfLV7WwyL91AocQrMD3retrtRY3pd5Ni93eMPitQxs6Zpuzzs0H9P5+7C3GaxsPIIcuhJoYb6h7Gf1HrkIKHPNUJOLG3cfx6HR9iF3g==,iv:XT4wEiibtBi8pNadspcSoU4GvWmfnUEaoGK0XP1WQg4=,tag:bUwhEUUqJFPG5neoRwJlZA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL1JsdHJHUUJWQ2pyRHQ3\nNXlTUWk3cndIRHU2bDJHdHM1N2svcVpJY0FNClo3V3prMmNFOXlRSE5sUGc0Y1pU\nU1N2b0o1ZTRQU2c0UmpSUzhkUFp5eUkKLS0tIEFtcE01UG9JRHpOejRNSXJ3NE9T\nK3dpUlBuSFV6K1prUkV5dTNDQ3VPblkKjsf0YK0gG1DnxYRRB+erN87NMQPIKeBH\nLf43I2WihAXtYx7mUiarrcxtbbnW3VDGLpbck+xR04iHmPkPSTEqag==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-25T20:21:53Z",
		"mac": "ENC[AES256_GCM,data:Aiq1l4qGJy/56DezyrsocX3plqPPKLLEiXErT91cSfEX4ciEnkaZqiEmH5hhZ4bARpV50tM6W691OWDBX6PuxysvhL3S4EIkdiia57TNM29J2zca9Sns5aaBpOb3WP4/kXXF0mOE+whuLlkL/i6YoaI/ODBXfgzSLt4XEznBSMg=,iv:qu7YrCdwv0l/BVex0YelptZq6FLyIBnaKg7DvFwW/Cs=,tag:GQ9Dv51LYHIPoNGWoo/pSw==,type:str]",
		"version": "3.11.0"
	}
}
