apiVersion: ENC[AES256_GCM,data:4pA=,iv:MRZzLe5eLgWPPViFLVw48AgRo4dMt27RSEtp6N7jsUw=,tag:clAcetMG/fc8do8Ktm+ogg==,type:str]
clusters:
    - cluster:
        server: ENC[AES256_GCM,data:1Wwme/RET5ZskIdTG1kEFHkBAwlLvugS5U0x/HGmSDtw,iv:VE+feO1KFg6QccVS/XMEL4QOTMnSKNtGPQ2v0SWB4NI=,tag:5QASiq2M9pjK7zMNDe4RgA==,type:str]
      name: ENC[AES256_GCM,data:B46RFRJlWks86QRc,iv:oQpEY+8iZecrU/JpHjYtgXD7tGrvYistybk7ztEB2v4=,tag:LEAsQo60k0km2Vjh++3MdQ==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:v+jPEK+iM0Z0apm7,iv:QyES20/SQXerXSUKUc2ND4LHHr9XdrIBRHfs4MqcIXo=,tag:RnjhFYEludF2ga/7ieA+OQ==,type:str]
        user: ENC[AES256_GCM,data:4ZeFMw==,iv:J//loHH9we4hABReifoCen5CQM50oiBpJT8o4Cx5CUk=,tag:7Egxoll3afOwqrmEikm2tA==,type:str]
      name: ENC[AES256_GCM,data:Fbbc1GitsVQoYHnC,iv:V8tApvsJLt3Eqkmgh0YL4mw1NFkUL/XgR1UKq9S4EOk=,tag:9L08XDypCJshvvsz+Ixe+w==,type:str]
current-context: ENC[AES256_GCM,data:ehrI26A3VZeED07u,iv:Wa0Dd/tQ+BKIGqJkIoyCsq+RJdkRZkxqRhrUiLGG9v4=,tag:Q2qkeAbvIm8LAZlfRGCOdg==,type:str]
kind: ENC[AES256_GCM,data:DDciyHbm,iv:pxR5VOjiMiEg+fLuCq8WOeRA9zCvI/UIcM5JzrEKx9Q=,tag:DDDKDixl+61pgUjZ1zRcrQ==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:1WAiXQ==,iv:IKTp5N28UcZ4qKbSL38zaI+cg6oTL09aKKk0H2bJr9U=,tag:kPou1dYtE7Ap4GWRZcL7rQ==,type:str]
      user:
        exec:
            apiVersion: ENC[AES256_GCM,data:zHqqFT91HhyoENQSWIvH5pXbBLwkYfDOPOLbK/pZXvkVYmiN,iv:BkADhs1sAnXMOUIGRk5UuXDTwSlx/Rlq+sctyivVYTc=,tag:xK+tKj2CXAuTBDiBCvi8Cw==,type:str]
            args:
                - ENC[AES256_GCM,data:6k1ucy55C9FjPQ==,iv:h6vmT6G55IZA5b0ZixXiHCe2JA+7AaE4MDBq4VFmn2k=,tag:xesjuOcsvl42aTCbswT7WA==,type:str]
                - ENC[AES256_GCM,data:OfoNB+/X8nNC,iv:mE3cYyHCmXfPe7AD06c61bpMrG8dU6xSWUetVlI2tbM=,tag:1u55ZVNupdNqs4cC7lPchw==,type:str]
                - ENC[AES256_GCM,data:oikdSJdjPFS5gD5KvJel0Q3EICL/qK/wpIeyEe8bWDezWJI5mNCS53FTl4WTZqLQpQ==,iv:iiKy3paQcwgxNJeqCEz34bl5Fk8GcHPTqm09hJpwAEU=,tag:+srS9A7TpNWERQgIN4vswg==,type:str]
                - ENC[AES256_GCM,data:xrU61K/1ztANhu8CFYNGeZUbhaC37xLXGfd8r681Gv3f2kCEWwaoxjFdoro/zcxOig==,iv:RDD1W217gc6suO4IHU5ycLDrCwcCnLyL2q22D54mcfo=,tag:MIkWKjzr7eh+OWPK4VG5zw==,type:str]
                - ENC[AES256_GCM,data:zw00+/VlorpoRYhzP7U3r8WvZaKZK9j8,iv:Y6MrQ4Ck/+XXkNK1jwN7eYKeFEmx1q+Qx9DmJIYGCtY=,tag:aMQdW04ZmJ5dIjJqR9h1uA==,type:str]
            command: ENC[AES256_GCM,data:DxN4KlF4BQ==,iv:Mm/y3ajWsH6rE0uqXdAukQMLf9FCTyQyjZno3WwyiMY=,tag:6cbauLFBkrNVYAYvuYZBpA==,type:str]
            env: null
            interactiveMode: ENC[AES256_GCM,data:6K1+sxHlM1pXEoA=,iv:TeZXlT7yjSbTG2pw93GKyYpI1QZTAUx5IiOWq7gQk4g=,tag:WF07K/8zZUsF10SRTNP2cA==,type:str]
            provideClusterInfo: ENC[AES256_GCM,data:s8bE+3s=,iv:sb89OSY9IJbw81hHgW8D80QBECRI8WjZYY6u6+VUNqU=,tag:a7m8P7drGc1d3MHNq0pyzw==,type:bool]
sops:
    age:
        - recipient: age1xrm9zv8a4uurywqazyg5m0p7p9jeh87dmyvhyghv6dq93w976dksy3xv5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM0pFamFuK1FlaHh3N2k3
            bDhhNTBaRTFvSVJTZHFFeW00Zk5XLzFyMVdjCkRHSG5NWXZUdnYrczhlNjdWeGtn
            NVdmemVvalNkYVNRckJXbHVvZU5rUGcKLS0tIGxOVHNqcWJ3bUk2cm1mbGJHQVhz
            WUFlK0s1MURLb2tsZVdkdWNBenpMekUKwckvjw/jnRQmWelSsl0+hTtm5SiDzJNY
            ubmb07E6KDK/cpfc84s3yTgI3pFwIK5CHKCO0So6xN3vDvjULB9GvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T20:54:44Z"
    mac: ENC[AES256_GCM,data:fWPCvI1a9f3i4RIFo1Mqk7WR2D2HnFLQ6j9ed54XaOxDtX474nmnl+CUa2S/j8mfatIC1S90x/Efr6e4G/ttZrsmlw3ctmRbZ0mrM8mE82H5lXuKbvq8gT4UQ+rbzBSGKzgeob8XE+doqXS6OB4zVFSHWZ0U5l4I2E9dDhzka2Y=,iv:jwRQNkpDyZOwse83+TUQN0HkN46dk3XAb1VjqTcuWO4=,tag:j+/gGyBKqAqUcmdRMwNd1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
