apiVersion: ENC[AES256_GCM,data:hlM=,iv:lvGqvHU2mbn2qaLMlTGeU9B11YzVw0qT7nfWVBi45fU=,tag:CIRHbOvgRsgLuYly543p+w==,type:str]
clusters:
    - cluster:
        server: ENC[AES256_GCM,data:ihYjFqlvEcbZBFRfVQaedLMLn+Jk7tsJ5iBlxYMepP3g,iv:IfX0v/t0UavjDbWAN9ep5dF41NZ5Xr8nwAvMeucC5YU=,tag:kH3rAdaIsHbDCdofvB+mrw==,type:str]
      name: ENC[AES256_GCM,data:+VU/M7Yced4F41TX,iv:t/wkn5Kzn9FIL//zzF9Y1YhJDKztLSQmlQHss/NUqsQ=,tag:W9OQo3U+zhiAOyB4bIYeNA==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:yuPlHcCD9Zm3jLz3,iv:QCQTd1ehkw5T/M7XUuAGI97DoFEBW+MSRv4tc1zP4h0=,tag:Nqo1kjVpSHxDCFTyXLJeCQ==,type:str]
        user: ENC[AES256_GCM,data:8F98Qw==,iv:U0IIqlJegaYspfkjnbr/BT15L7Qv7tyl9srGVbHY6OE=,tag:Idiks7xpvJjO7w6g7QtnBg==,type:str]
      name: ENC[AES256_GCM,data:dfD/Pc6wvjDwV4qH,iv:AxBwxruETB8xRWVhRyzYd9if2/pjJZCsk09mhm8tnS0=,tag:0sUQ7Ugcc/MNTkRM/pI1zg==,type:str]
current-context: ENC[AES256_GCM,data:EHI8YJn1FK4Vnc81,iv:1d77aPDbCcPRGQN55wFJaz9xNLb9ct5B+Rk0GfsBlrc=,tag:Sc2efXwgaoBT+p9ofOZE5Q==,type:str]
kind: ENC[AES256_GCM,data:1FtBXbRw,iv:+2YXGVAarAndEvNuOS2zfkU/XsOuJa+ou5+XMb7Es8g=,tag:dVJ4WCU1pGquu5mQDOl//w==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:XU11uA==,iv:mv4iFcJaVAI6Tro8+BXbsUHifYD2MjENCoJwH0Z7ivc=,tag:C5ZJh5FoGXOdYD+93C7XMw==,type:str]
      user:
        exec:
            apiVersion: ENC[AES256_GCM,data:7UZ3kqMuLcRlI8eSWyMNsvRxgNJt82yWuqbnC7Yy8txVdKxw,iv:hP1Np5I2v00GCgvbacEYJWJwHd3pZY4MT9fLn+XCwdk=,tag:y3i5ZBd6VbudVLP1cC1fvQ==,type:str]
            args:
                - ENC[AES256_GCM,data:t8LEo+ozdx65ZA==,iv:NId0ENHo16Q4ct64otSfw78oTdjlb2f3i6mvot0tps0=,tag:VrSdTumstuDGfLcvjQTZ7Q==,type:str]
                - ENC[AES256_GCM,data:T0QnrJWdQtdM,iv:+BHusGIs4EqO2Gg0mOBjo0M5mowMtAk9O7jUId+2eBQ=,tag:byD7quOVj/DjbS7rVxylYA==,type:str]
                - ENC[AES256_GCM,data:g2CtHKoO1aUQRghAW1t6bV4rf/7CI8TDlD9VPq/Z8EJEZRrKdN4yJYZ4+XtPOgkTEw==,iv:LhiokCLIGNnSlYy7gCAos3LKR58AkVPQ/cYKFjAEzJA=,tag:Imrzo3AF5r/gBuzdssjXcw==,type:str]
                - ENC[AES256_GCM,data:YQ5zJtsOSvEQ4JLqFm6V/9N+3NYEtrCWYoxwdVnJk6zvg6fu8I2hBtP0qz9GjG3agA==,iv:nfJzVMzi6SW4VtNlFHwaCLdwpv6OyAXjYeag91FLad0=,tag:sSIAN41JgRjvrSCW0DYy9w==,type:str]
                - ENC[AES256_GCM,data:1sHLWwbnb5i4TDxQpKPK3fy9S8fcQ976,iv:IDX/ibQNNmJo33FmGGYZzoQ84t8iz5WNfCGIOkPhhes=,tag:9ywr2r9aagDIdLf87XjNeA==,type:str]
            command: ENC[AES256_GCM,data:Xoc787H6Sw==,iv:lzdSHZ4aJyRFxLRwxaT1Nc4csSqSekkNRFzgkqk6lik=,tag:A+i8qLbL5A0xC1LKetZJ8A==,type:str]
            env: null
            interactiveMode: ENC[AES256_GCM,data:FF4lewvKmil6iDs=,iv:fAX6I/KqzbKgOTIT5FgnGEXEPOa2d1QrxVZKG6HyMNk=,tag:79ofnclK8J7utlreOtIFpg==,type:str]
            provideClusterInfo: ENC[AES256_GCM,data:v/nLX0U=,iv:U2DayXac5mIxXPlz6whxT5hNOF724NwOx7b1sOXF2co=,tag:FixIo95pDGbtw8DaMe4QyQ==,type:bool]
sops:
    age:
        - recipient: age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RHR0Yzdlbll2SGFQZUZj
            RXcrN0l6UFZSSWxDelhnUUNZcE0ycFlMY0E4Ci9mVkZTZHFWZCtOKyt5dkljV21a
            TlErMUw1QXFmMGtBMEllcUZPUmVpWXcKLS0tIEJGOEVqSitYNmgrbkpDZTlPQ2lt
            eUptREZZNXVIaUpLV21GSHNmZ3FrVFkKxJk4NTrZhwA2++ZRsTSAyzlBfItBSCBB
            7clzZyO+hTCWIILRwQERQ2Tjb2MdgOzQuGN7kyu28RVwkuV/xynhqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T01:11:13Z"
    mac: ENC[AES256_GCM,data:CWaVKVCd4hctdUPnAfgc3J7/ybcWL5Vzv0dC7mrOt5mce7TY80ElPkqN8jpYfUf9ODV22Ei8WNl9/CecR++bEZ+zDK69o/KPlhVz5MdCqd9NP7jhx2yikyjbjW7eHk7BI4xC2egR+PHg3DrXc3pdtVUD2BUc9fJ/hkwlo652va0=,iv:ioNDBJLBUfrBPPRERbGxYlTbrg6BjQaeKksqHRNGoRw=,tag:fvSV3KrA6tHMEW7ta3GJjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
