apiVersion: ENC[AES256_GCM,data:2nk=,iv:RjK020bmTR5H721nigKygdzQzNSbPckp+N6IX6cKQB8=,tag:4a1GzAGwUV8SyIY4i7+Ghw==,type:str]
clusters:
    - cluster:
        server: ENC[AES256_GCM,data:nSLM83IF0M/I1hbZEtT/TfSZ5uTs1npoHhD3b3BcJE7wr8uXlBaeYV4=,iv:XuqeLh5q2eb8Uy48KSMtJYiWSmast6NIdqTR5slAbyE=,tag:a1yS20nGszUEU78Y+73LTQ==,type:str]
      name: ENC[AES256_GCM,data:tL3TWyYXisypBHwC,iv:8Q9eYXOpg/pZSxohTEl4e1uTkt2W3C6cgP9BLjo9BN0=,tag:xv7tyIJw/XPFhw3D2qfwxA==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:wETRjBTGelnuO7jO,iv:UdiCWgNK+HI9s03jv5Z6qo+rYjrtSzcP7TTHwgoJK3A=,tag:7Ui+YpiZsl7HbFSVtaQxmw==,type:str]
        user: ENC[AES256_GCM,data:TV9ZZw==,iv:BJR2yiLmDyl4eWKF94ajO3Es8XKKUzen4yok0fBprFY=,tag:R/+4QLQk3E6alKqsWtqRQw==,type:str]
      name: ENC[AES256_GCM,data:dpyaibd3f00E2Mst,iv:D/CKCYfzrx2ErtSN5T9rqwmxXuB6qsJlf3iKJ58GsOk=,tag:krlmZsgdh0tbUw7vKoSrMQ==,type:str]
current-context: ENC[AES256_GCM,data:2ZWDNJpQEUfF4qdw,iv:dcVBsT9VW1JdIzKT+J2RtDe2btkKRiknqg4F1ekSjgQ=,tag:e06i7Dus9aTtJs8X1B3LDA==,type:str]
kind: ENC[AES256_GCM,data:TQ1F4Vif,iv:DdECJYd7xzKAun3Fqj63Zj+DdQGU6mCvGaDpS7/4TqU=,tag:mb/ZHhsq3OlnDdrsMgOt7g==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:mhpQ9w==,iv:G73WXzWNEOQ6hkeHLI4ShZs3WrybY/9m/gP4WgHfDAA=,tag:zWumVGBkLib6Xtng2DeMsw==,type:str]
      user:
        exec:
            apiVersion: ENC[AES256_GCM,data:NkEFqXC/ajkspN0CI8DEXdHWPwFi7NokB1TMADDv8bz1/MVH,iv:dnMtNyKKqg+/rf1VvwAnIMai5T8ZJlgDuevIeh2riNE=,tag:dIAHBF0/TTIob6SJ+oFP2A==,type:str]
            args:
                - ENC[AES256_GCM,data:N5Lmxy6Q3xwZ7Q==,iv:PhXhOciWgUK00gpISUFUMQ1qZJKuNVU7NvBlpnWZQDM=,tag:E7Z8bWqIuAuqvMqgAEqiwA==,type:str]
                - ENC[AES256_GCM,data:uf8fMnZ5OMv6,iv:6GjiqaycG1OAhJ2xtDbfARmdfQk9rDzHE/NJ4CLEIRw=,tag:5l/Q+iAbqQrFFhOgnyDlVQ==,type:str]
                - ENC[AES256_GCM,data:cHp7UcMdGBNJbSwIwAaBLyCy5g5o33OYAbFvVozbRZ9gbnbwPXy70zJQWFTI4w96eQ==,iv:0sfCtfyyKQ1/xgiD7oABbnECYCFrMQXK5merI5n1ILQ=,tag:f2cUcXhn3XDZJgY3Pu1s7Q==,type:str]
                - ENC[AES256_GCM,data:pTltPFgigE3myJ1c8lbj4Z7Q8aH3H7V9Ht00Cncf7o5r3z/dvXAQqZ8Lg6URcyDWmg==,iv:SYmMQhLmzK1lTx7U1su89BrhJxwYzGSFrYBQbnSFqnE=,tag:TmDtd3ija9tlZZTTKENC9w==,type:str]
                - ENC[AES256_GCM,data:bVWmV2ImE24RBlvVZd5QsTNCxAH7iOBi,iv:QuPPHMH4dKzs5SYRYVy0b6YU9JvNipcqNPU6bFPGajQ=,tag:JBA0gZ22lMbT8qmW0iGQCQ==,type:str]
            command: ENC[AES256_GCM,data:KHlpxR4kGA==,iv:Wu1NEvK5fTOWRns/83Tp7+C/odtNYf6x7jP44q+zdjA=,tag:L4/zxeziYsDpZ7ai9Tve7w==,type:str]
            env: null
            interactiveMode: ENC[AES256_GCM,data:u9TVmIHECKZwkGY=,iv:3W/ahQ9IMUz0Hwp6sgqYIWKKdzA5g0W2nJ+RgNsKGEk=,tag:btcQttZdoslIrmkvjRfeGg==,type:str]
            provideClusterInfo: ENC[AES256_GCM,data:xHENwhU=,iv:qL864Q0c/8wvmMzhjNmTv1fh/0Q+r5AZ8G0R5x/n/m0=,tag:mBusdCAXaUv1nv2tLlg10A==,type:bool]
sops:
    age:
        - recipient: age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcFE5cFNBeHB4RzA2L0NP
            QmZkM3g5aW0rbm9JMzFSV2RkZEVXWElXQ0ZVCmFRblh4S1JGSVQ2YjRJNkdldWM1
            UU13YVNadUhmdTlueTdETnRJWjJTcDQKLS0tIHVyVkV5ZTVsaW9LNkkxbTRmdmQx
            RVJtMzYyd3hTdUYwQU1va255T0w5bHcKJdGz/PqHhHvIbPeTyPN9mMUhAhVRiA6x
            5rkuHPMssEE1bNVQwKE1bYqWvWQvzT42lvgIB9Cr+25bH4+TWWseng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T18:34:33Z"
    mac: ENC[AES256_GCM,data:t7pWDEJehfn4VjXawnf/qJsy0D10dL92gB9eBwVHlIv0+wkBo2eJX9vYOll2024laV3xk+MMqT3WKYKTfwrh24lYkkIMYSpyKFIVqRFbFR2eaKAm026l4fPukvjJ08bT82dBgrn+wkPw4WFUYLjUy9bxA+XJm6sag/ztxLYjV2w=,iv:7xP0P6cKYfhmMsjN5r4mnKZr0X2QjDZsgMndytuFTdM=,tag:Koj9wBi4C7gxjFA9cSDlew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
