age_keys: &age_keys
  - "age1ktfsdqtzs3c84krtw62rjumqhf4fvf8acqauv5x6cr883wgj53sq5df9y6" # local
  - "age1d0jrt7mlu50t4f0wh0t9hrdt23tjx92k57exc3gukx8e87fq35tshxc3as" # nixos-mini3

creation_rules:
  - path_regex: .*.(yaml|yml|json|env)$
    age: *age_keys
